name: Deploy Backend

on:
  push:
    branches: [feature-java21]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/vehicle_server
            git pull origin feature-java21
            docker compose build --no-cache
            docker compose up -d
